package Exception_Handling.Uebungen;

public class TestPersonenalter {
    public static void main(String[] args) throws OutOfRangeException {
        new Personenalter(160);
    }
}
